baseURL                   = "https://blog.1wenzone.com/"
builddrafts                = false       # 構建草稿
languageCode               = "zn-TW"   # 語言
canonifyurls               = true        # 規範化網址
contentdir                 = "content"      # 內容目錄
layoutdir                  = "layouts"      
publishdir                 = "public"     
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "1WenZone"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/pc.png"               # from static/
  avatar                   = "img/S__37740553.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "1WenZone"
  description              = ["食記|遊戲|程式|生活", "明天的煩惱就留給明天", "Do the right things and be a better man."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "c5566_821130@yahoo.com.tw"
  github                   = ""
  linkedin                 = "linkedin.com/in/kevin-chen-302156177"
  facebook                 = ""
  googleplus               = ""
  twitter                  = "" 
  px500                    = ""
  instagram                = ""
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    